[package]
name = "frontend"
version.workspace = true 
edition.workspace = true

[dependencies]
leptos = { version = "0.7", features = ["csr"] }
reqwest = { version = "0.12.9",features = ["json"]}
common = { workspace = true }
leptos_router = "0.7.0"
leptos_router_macro = "0.7.0"
