[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }
common = { workspace = true }
