[package]
name = "partitions"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["process","fs"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
