[package]
name = "webls_app"
version.workspace = true
edition.workspace = true

[dependencies]
get-port = "4.0.0"
iced = "0.13.1"
local-ip-address = "0.6.3"
webls = {workspace = true,features = ["ssr"]}
