[package]
name = "delivery"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true , features = ["json","multipart"] }
common.workspace = true
tokio = { workspace = true , features = ["fs"] ,optional = true}

[features]
native = ["dep:tokio"]
