[package]
name = "delivery"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true , features = ["json","multipart"] }
common.workspace = true
gloo.workspace = true
tokio = { workspace = true , features = ["fs"] }
web-sys.workspace = true
